In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [ ]:
b = np.array([[4.0, 5.0, 6.0],[7.0, 8.0, 9.0]])
print(b)

[[4. 5. 6.]
 [7. 8. 9.]]


###Get Dimension

In [ ]:
a.ndim

1

In [ ]:
b.ndim

2

###Get Shape

In [ ]:
a.shape

(3,)

In [ ]:
b.shape

(2, 3)

###Get Type

In [ ]:
a.dtype

dtype('int32')

In [ ]:
b.dtype

dtype('float64')

###Get Item Size (Byte)

In [ ]:
a.itemsize

4

In [ ]:
b.itemsize

8

###Get total size

In [ ]:
a.size * a.itemsize
#or
a.nbytes

12

In [ ]:
b.size * b.itemsize
#or
b.nbytes

48

#Accessing/Changing Specific Elements, Rows, Columns etc..

In [ ]:
c = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
#Shape
c.shape

(2, 7)

###Get Specific Element. Rule --> [row, column]

In [ ]:
c[0,-2]

6

###Get Specific Row

In [ ]:
c[1, :]

array([ 8,  9, 10, 11, 12, 13, 14])

###Get Specific Column

In [ ]:
c[:, 5]

array([ 6, 13])

###Getting a little bit fancy [start:end:step]

In [ ]:
c[1, 2:-1:1]

array([10, 11, 12, 13])