In [2]:
import numpy as np

In [ ]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [ ]:
b = np.array([[4.0, 5.0, 6.0],[7.0, 8.0, 9.0]])
print(b)

[[4. 5. 6.]
 [7. 8. 9.]]


###Get Dimension

In [ ]:
a.ndim

1

In [ ]:
b.ndim

2

###Get Shape

In [ ]:
a.shape

(3,)

In [ ]:
b.shape

(2, 3)

###Get Type

In [ ]:
a.dtype

dtype('int32')

In [ ]:
b.dtype

dtype('float64')

###Get Item Size (Byte)

In [ ]:
a.itemsize

4

In [ ]:
b.itemsize

8

###Get total size

In [ ]:
a.size * a.itemsize
#or
a.nbytes

12

In [ ]:
b.size * b.itemsize
#or
b.nbytes

48

#Accessing/Changing Specific Elements, Rows, Columns etc..

In [3]:
c = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [4]:
#Shape
c.shape

(2, 7)

###Get Specific Element. Rule --> [row, column]

In [5]:
c[0,-2]

6

###Get Specific Row

In [6]:
c[1, :]

array([ 8,  9, 10, 11, 12, 13, 14])

###Get Specific Column

In [7]:
c[:, 5]

array([ 6, 13])

###Getting a little bit fancy [start:end:step]

In [8]:
c[1, 2:-1:1]

array([10, 11, 12, 13])

###Change Specific Value

In [10]:
c[1,6] = 15
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 15]]


###Change Specific Column Value

In [11]:
c[:,6] = [8,16]
print(c)

[[ 1  2  3  4  5  6  8]
 [ 8  9 10 11 12 13 16]]


##3D Array Example

###Get Specific Element (Work Outside In)

In [15]:
d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [16]:
d.ndim

3

In [20]:
d[:,0,1]

array([2, 8])

In [21]:
d[0,1,1]

5

In [22]:
d[1,0,2]

9

###Replace

In [23]:
d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [25]:
d[:,:,2] = [[0, 0],[0, 0]]

In [26]:
d

array([[[ 1,  2,  0],
        [ 4,  5,  0]],

       [[ 7,  8,  0],
        [10, 11,  0]]])

##All  Different Types of Arrays

###All 0's Matrix

In [44]:
e = np.zeros((4,3,2), dtype='int32')
print(e)

[[[0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]]]


In [43]:
e.ndim

3

###All 1's Matrix

In [49]:
f = np.ones((2,3,2), dtype='int32')
print(f)

[[[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]]


In [50]:
f.ndim

3

###Any other Matrix Create --> full method ((number_of_matrix or dimension),value)

In [52]:
g = np.full((3,3),10)
print(g)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


###Any other number like --> full_like method (variable, value)

In [54]:
h = np.full_like(c, 1)
print(h)

[[1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]]


###Random Decimal Numbers

In [60]:
i = np.random.rand(3,3)
print(i)

[[0.54878812 0.47731931 0.55062178]
 [0.89796986 0.96143643 0.15730864]
 [0.22348762 0.31370735 0.02354584]]


In [61]:
j = np.random.random_sample(c.shape)
print(j)

[[0.19982951 0.62967914 0.12467048 0.03394525 0.07639077 0.65107999
  0.16901841]
 [0.51616571 0.75296722 0.4070767  0.62972582 0.07784153 0.08416515
  0.12063687]]


###Random Integer Numbers

In [64]:
k = np.random.randint(1, 9, size=(3,3))
print(k)

[[7 5 8]
 [2 7 2]
 [5 1 7]]


###Identity Matrix

In [68]:
l = np.identity(5, dtype='int32')
print(l)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
